api/src/main/resources/db/changelog/db.changelog-payment-instruction.yaml

although this role column in this format is temporary but to not to throw error on the server let's update the column varchar size

[AK] change role column size in user

---

api/build.gradle

add-exclusions-to-avoid-version-clash

---

api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java

fix send-to-payhub url mapping

---

api/src/main/resources/application.properties
build.gradle
gradle/wrapper/gradle-wrapper.properties

(cherry picked from commit cb82423)

upgrade to spring 2.1.0

---

api/build.gradle
api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstruction.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionSearchCriteriaDto.java
api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionStatusRepository.java
api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionsSpecifications.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/ComponentTestBase.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PaymentInstructionUserFilterTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/utils/DbTestUtil.java
api/src/test/java/uk/gov/hmcts/bar/api/controllers/PaymentInstructionSearchTest.java
api/src/test/java/uk/gov/hmcts/bar/api/controllers/PaymentInstructionStatsTest.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java
build.gradle

[BAR-556][AK] List rejected items for senior fee-clerk the same way as any other payment instructions

Bar 556 list reject

---

api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionStatusRepository.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java

- [&#10004;] commit messages are meaningful and follow good commit message guidelines
- [&#10004;] README and other documentation has been updated / added (if needed)
- [&#10004;] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/BAR-671
This PR is for adding site-id to the queries which collects lists the rejected items by the approver, and the submitted items by the fee-clerks
It does not have any bar-web related changes or dependencies.
```
[ ] Yes
[X] No
```

 [BAR-671][AK] Add site-id to pi-stats endpoint request to filter users and the related numbers

---

infrastructure/saat.tfvars

switch idam url to http from https.

---

api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstruction.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionStatus.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionStatusCriteriaDto.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionStatusReferenceKey.java
api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionStatusRepository.java
api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionStatusSpecifications.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/FullRemissionService.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java

https://tools.hmcts.net/jira/browse/BAR-678
Stats on reviewer and approver page filtered by siteId and only showing numbers related to the site where the logged-in user belongs to
```
[ ] Yes
[X] No
```

[BAR-678] Approver list stats

---

infrastructure/aat.tfvars

update idam url to the strategic one on aat

---

api/src/main/resources/bootstrap.yaml
charts/bar-api/values.template.yaml

s2s vault for retrieving totp
```
[ ] Yes
[x ] No
```

using s2s vault for retrieving totp

---

dependency-check-suppressions.xml

Spring Security contains an authorization bypass when using method security
https://nvd.nist.gov/vuln/detail/CVE-2018-1258

CVE-2018-1258 - suppression

---

api/src/functionalTest/java/uk/gove/hmcts/bar/functional/AuthenticatorClient.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/FunctionalTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/PaymentInstructionCreationTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/ReferenceDataTest.java
api/src/test/resources/functional-test.properties
charts/bar-api/values.aat.template.yaml

Creating client to retrieve the auth token
https://tools.hmcts.net/jira/browse/BAR-706
Adding functional tests for bar-apps, creating a java http client to retrieve the authtoken from idam
```
[ ] Yes
[X] No
```

[BAR-706][AK] Functional testing of api.

---

api/src/functionalTest/java/uk/gove/hmcts/bar/functional/AuthenticatorClient.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/FunctionalTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/PaymentInstructionCreationTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/PaymentInstructionUpdateTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/ReferenceDataTest.java
api/src/main/java/uk/gov/hmcts/bar/api/data/exceptions/PaymentInstructionNotFoundException.java
api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionRepository.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java
api/src/test/resources/functional-test.properties
charts/bar-api/values.aat.template.yaml

https://tools.hmcts.net/jira/browse/BAR-708
This PR built on the top of BAR-706. Added new functional tests to cover when update a payment from a different site. Also contains the code change to make sure the test pass.
```
[ ] Yes
[X] No
```

[BAR-708][AK] Functional test for editing payment from another site

---

infrastructure/demo.tfvars

idam - repoint demo to aat

---

api/src/functionalTest/java/uk/gove/hmcts/bar/functional/CaseFeeDetailTest.java
api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/CaseFeeDetailService.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/AllPayInstructionCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/CashInstructionCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/ChequeInstructionCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/ComponentTestBase.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PostalOrderCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/CaseFeeDetailServiceTest.java

BAR-709 implemented

---

build.gradle

upgrade spring version
```
[ ] Yes
[x] No
```

upgrade spring boot version to 2.1.4.

---

api/src/main/java/uk/gov/hmcts/bar/api/converters/PaymentInstructionsCsvConverter.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/BasePaymentInstruction.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstruction.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionReportLine.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PaymentInstructionCsvRetrieveTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/utils/DbTestUtil.java

BAR-612 implemented

---

api/src/functionalTest/java/uk/gove/hmcts/bar/functional/FunctionalTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/PaymentInstructionUpdateTest.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/main/java/uk/gov/hmcts/bar/api/data/validators/FullRemissionValidator.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionUpdateValidatorServiceTest.java

https://tools.hmcts.net/jira/browse/BAR-719
Fix return/withdraw full remission, and covering with unit and functional tests
```
[ ] Yes
[X] No
```

[BAR-719][AK] Fix return/withdraw full remission

---

api/src/functionalTest/java/uk/gove/hmcts/bar/functional/FunctionalTest.java

modify functional tests to use proxy to be able to access aat from local
```
[ ] Yes
[x] No
```

add proxy settings when needed to rest assured client

---

api/src/functionalTest/java/uk/gove/hmcts/bar/functional/FunctionalTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/SendToPayhubTest.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionPayhubReference.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/data/PayhubFullRemission.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/data/PayhubPaymentInstruction.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/repository/PayhubFullRemissionRepository.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/repository/PayhubPaymentInstructionRepository.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/service/PayHubService.java
api/src/test/java/uk/gov/hmcts/bar/api/data/TestUtils.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java
api/src/test/java/uk/gov/hmcts/bar/api/integration/payhub/service/PayHubServiceTest.java
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/BAR-682
Send full-remission to payhub
```
[ ] Yes
[X] No
```

[BAR-682][AK] Send full-remission to payhub

---

api/src/main/java/uk/gov/hmcts/bar/api/data/model/BasePaymentInstruction.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/data/PayhubPartialRemission.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/service/PayHubService.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PayhubIntegrationTest.java
api/src/test/java/uk/gov/hmcts/bar/api/data/TestUtils.java
api/src/test/java/uk/gov/hmcts/bar/api/integration/payhub/service/PayHubServiceTest.java

https://tools.hmcts.net/jira/browse/BAR-757
Modify payhub integration to send partial-remission to payhub as well
```
[ ] Yes
[X] No
```

[BAR-757][AK] Send partial remission to payhub

---

api/src/main/java/uk/gov/hmcts/bar/api/configuration/SpringSecurityConfiguration.java
api/src/main/java/uk/gov/hmcts/bar/multisite/controller/SiteController.java
api/src/test/java/uk/gov/hmcts/bar/multisite/controller/SiteControllerIntegrationTest.java
api/src/test/java/uk/gov/hmcts/bar/multisite/controller/SiteControllerTest.java

https://tools.hmcts.net/jira/browse/BAR-626
Add /sites/my-sites endpoint to be able to list sites for an authenticated user
```
[ ] Yes
[X] No
```

[BAR-626][AK] add self-check endpoint to sites micro-service

---

api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/service/PayHubService.java
api/src/main/java/uk/gov/hmcts/bar/multisite/controller/SiteController.java
api/src/main/java/uk/gov/hmcts/bar/multisite/model/Site.java
api/src/main/java/uk/gov/hmcts/bar/multisite/model/SiteUserDto.java
api/src/main/java/uk/gov/hmcts/bar/multisite/repository/SiteRepository.java
api/src/main/java/uk/gov/hmcts/bar/multisite/service/SiteService.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/ComponentTestBase.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/utils/DbTestUtil.java
api/src/test/java/uk/gov/hmcts/bar/multisite/controller/SiteControllerIntegrationTest.java
api/src/test/java/uk/gov/hmcts/bar/multisite/controller/SiteControllerTest.java
api/src/test/java/uk/gov/hmcts/bar/multisite/service/SiteServiceTest.java
api/src/test/java/uk/gov/hmcts/bar/multisite/utils/SiteUtils.java
build.gradle

https://tools.hmcts.net/jira/browse/BAR-772
Getting full name of site user from bar(idam)
```
[ ] Yes
[X] No
```

[BAR-772][AK] retrieve full name for site user

---

api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java
build.gradle

BAR-792 implemented

---

api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/BAR-661
Start date is always from 00:00:00 and the end date is until 23:59:59
```
[ ] Yes
[X] No
```

[BAR-661][AK] Fix search when same start end date issue

---

api/src/main/java/uk/gov/hmcts/bar/api/data/model/BasePaymentInstruction.java

https://tools.hmcts.net/jira/browse/BAR-812
Change column heading in BAR Reports to align with values on GUI.
```
[ ] Yes
[x ] No
```

BAR-812 CSV header changes

---

api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstruction.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionPayhubReference.java
api/src/main/java/uk/gov/hmcts/bar/api/data/model/PaymentInstructionSearchCriteriaDto.java
api/src/main/java/uk/gov/hmcts/bar/api/data/repository/PaymentInstructionsSpecifications.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/data/PayhubFullRemission.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/data/PayhubPartialRemission.java
api/src/main/java/uk/gov/hmcts/bar/api/integration/payhub/data/PayhubPaymentInstruction.java
api/src/main/resources/db/changelog/db.changelog-payment-instruction.yaml

BAR-803 implemented

---

api/src/main/resources/db/changelog/db.changelog-payment-instruction.yaml

https://tools.hmcts.net/jira/browse/BAR-820
Adding idam user registration feature toggle
```
[ ] Yes
[X] No
```

[BAR-820][AK] User registration feature

---

api/build.gradle
build.gradle
dependency-check-suppressions.xml

Update all the dependencies to the latest one
```
[ ] Yes
[Xx] No
```

[AK] Dependency check update

---

infrastructure/main.tf

add subscription var to db module

---

infrastructure/main.tf

fix parsing error

---

infrastructure/main.tf

Add subscription

---

charts/bar-api/Chart.yaml

[AK] Update helm version to get the latest bar-api from master

---

Dockerfile
docker-compose.yml

Update urls in docker files to use the latest repos and images
```
[ ] Yes
[X] No
```

[AK] update docker image to use the updated repos

---

web.config

[AK] add new appinsight lib to web.config

---

infrastructure/main.tf

Build Issue fix for Vault changes
```
[ ] Yes
[ x] No
```

Build Issue fix for Vault changes

---

infrastructure/main.tf

Build failure fix for vault changes
```
[ ] Yes
[x ] No
```

Build failure fix for vault changes

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/saat.tfvars

Payment API URL modified for build fix.
```
[ ] Yes
[ x] No
```

Payment API URL modified for build fix.

---

infrastructure/variables.tf

Payment API variable added for build fix
```
[ ] Yes
[ x] No
```

Payment API variable added for build fix

---

Dockerfile
Jenkinsfile_CNP
api/build.gradle
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/SendToPayhubTest.java
api/src/main/resources/application.properties
api/src/main/resources/bootstrap.yaml
build.gradle
charts/bar-api/Chart.yaml
charts/bar-api/requirements.yaml
charts/bar-api/values.aat.template.yaml
charts/bar-api/values.preview.template.yaml
charts/bar-api/values.yaml
dependency-check-suppressions.xml
infrastructure/main.tf
infrastructure/variables.tf
web.config

Aks migration

---

charts/bar-api/Chart.yaml
charts/bar-api/values.yaml

https://tools.hmcts.net/jira/browse/BAR-877
updated the keyvault
```
[ ] Yes
[X ] No
```

keyvault update

---

api/src/main/resources/bootstrap.yaml

update the secrete name
```
[ ] Yes
[X ] No
```

update the secret name

---

api/src/main/resources/bootstrap.yaml

Fix appinsights notation to make it work

---

dependency-check-suppressions.xml

added vulnerabilities

---

.travis.yml
charts/bar-api/Chart.yaml
charts/bar-api/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/PAY-2612
Helm upgrade changes
```
[ ] Yes
[x] No
```

Helm upgrade changes

---

build.gradle

https://tools.hmcts.net/jira/browse/BAR-938
Handling/Removing CVE errors
```
[ ] Yes
[x] No
```

Handling CVE errors

---

api/src/main/java/uk/gov/hmcts/bar/multisite/model/SiteUserDto.java
api/src/main/java/uk/gov/hmcts/bar/multisite/repository/SiteRepository.java
api/src/main/java/uk/gov/hmcts/bar/multisite/service/SiteService.java
api/src/test/java/uk/gov/hmcts/bar/multisite/service/SiteServiceTest.java
api/src/test/java/uk/gov/hmcts/bar/multisite/utils/SiteUtils.java
dependency-check-suppressions.xml

- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```

adding roles in endpoint

---

Jenkinsfile_nightly
audit.json
dependency-check-suppressions.xml
security.sh

Mutation tests

---

Jenkinsfile_nightly

update jenkins file for nightly build

---

Jenkinsfile_CNP
charts/bar-api/values.preview.template.yaml
dependency-check-suppressions.xml

suppress CVE's BAR-1052

---

audit.json

added fix for nightly build

---

api/build.gradle
api/src/main/java/uk/gov/hmcts/bar/api/configuration/AppConfig.java
api/src/main/java/uk/gov/hmcts/bar/api/controllers/payment/PaymentInstructionController.java
api/src/main/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionService.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/AllPayInstructionCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/CardInstructionCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/CashInstructionCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/ChequeInstructionCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/PostalOrderCrudComponentTest.java
api/src/test/java/uk/gov/hmcts/bar/api/controllers/PaymentInstructionStatsTest.java
api/src/test/java/uk/gov/hmcts/bar/api/data/service/PaymentInstructionServiceTest.java
build.gradle
dependency-check-suppressions.xml

BAR -1091 - Spring boot version upgrade changes

BAR-1091-Spring boot version Upgrade

---

dependency-check-suppressions.xml

PAY-3846 : nightly build issue fix

---

docker-compose.yml

local idam added

---

dependency-check-suppressions.xml

supressions added

---

api/build.gradle
build.gradle
client/build.gradle

fixed for jackson, tomcat core and websocket CVEs

---

api/build.gradle
api/src/main/java/uk/gov/hmcts/bar/api/auth/SiteValidationFilter.java
api/src/main/java/uk/gov/hmcts/bar/api/configuration/SpringSecurityConfiguration.java
api/src/main/resources/application.properties
build.gradle
charts/bar-api/Chart.yaml
charts/bar-api/requirements.yaml
charts/bar-api/values.yaml
dependency-check-suppressions.xml

1) Java chart upgrade from 2.x to 3.x
2) Spring boot version upgrade changes
3) Graceful shutdown changes

Pay 3831 helm upgrade

---

api/build.gradle
api/src/main/java/uk/gov/hmcts/bar/api/auth/SiteValidationFilter.java
api/src/main/java/uk/gov/hmcts/bar/api/configuration/SpringSecurityConfiguration.java
api/src/main/resources/application.properties
build.gradle
charts/bar-api/Chart.yaml
charts/bar-api/requirements.yaml
charts/bar-api/values.yaml

Revert "Pay 3831 helm upgrade"

---

build.gradle
cve-resolution-strategy.gradle
dependency-check-suppressions.xml

Bar API CVE fix

---

dependency-check-suppressions.xml

PAY-4085 : Nightly Build issue fix

---

charts/bar-api/Chart.yaml
charts/bar-api/values.yaml
docker/database/Dockerfile
infrastructure/main.tf
infrastructure/variables.tf

PAY-3979-DB-Upgrade : DB Upgrade from v9.6 to v11

---

audit.json

PAY-4179-Security Scan issue fix

---

build.gradle
dependency-check-suppressions.xml
infrastructure/main.tf

PAY-4118-old database instance de-commissioning

---

.gitignore
Jenkinsfile_CNP
api/build.gradle
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/CaseFeeDetailTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/PaymentInstructionCreationTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/PaymentInstructionUpdateTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/ReferenceDataTest.java
api/src/functionalTest/java/uk/gove/hmcts/bar/functional/SendToPayhubTest.java

https://tools.hmcts.net/jira/browse/PAY-3407
Serenity report functionality to BAR APP
```
[ ] Yes
[x] No
```

Added serenity report functionality to BAR APP

---

Jenkinsfile_nightly
cve-resolution-strategy.gradle

PAY-4435 : fix the cve

---

dependency-check-suppressions.xml

Nightly build issue fix

---

api/src/functionalTest/java/uk/gove/hmcts/bar/functional/SendToPayhubTest.java
cve-resolution-strategy.gradle

Modified Functional Tests

---

cve-resolution-strategy.gradle
dependency-check-suppressions.xml

Nightly dev

---

Jenkinsfile_nightly

build issue fix

---

cve-resolution-strategy.gradle
dependency-check-suppressions.xml

CVE Fix : CVE-2021-22096

---

cve-resolution-strategy.gradle

log4j upgrade

---

cve-resolution-strategy.gradle

log4j upgrade to 2.16.0

---

config/fortify-client.properties

added new fortify release Id

---

cve-resolution-strategy.gradle
dependency-check-suppressions.xml

fixed cve issues 04 feb 2022

---

cve-resolution-strategy.gradle

updated CVE fixes

---

charts/bar-api/Chart.yaml

updating chart to newest release

---

cve-resolution-strategy.gradle
dependency-check-suppressions.xml

cve fixes 24 march 2022

---

dependency-check-suppressions.xml

supressing spring-core issue, not version with a fix exists.

---

security.sh

testing fixes for nightly-dev

---

Jenkinsfile_nightly
dependency-check-suppressions.xml

Extend cve date to 30/09/2022 and disable night job for nightly branch

---

cve-resolution-strategy.gradle
dependency-check-suppressions.xml

updating tomcat embed core version

---

dependency-check-suppressions.xml

CVE-2022-31569 and CVE-2022-31548

---

charts/bar-api/Chart.yaml
charts/bar-api/values.preview.template.yaml

PAY-5683 Java version upgrade in chart yaml

---

charts/bar-api/values.preview.template.yaml

Fix fortify scan issue for username

---

cve-resolution-strategy.gradle

upgraded postgres version to fix cve

---

dependency-check-suppressions.xml

adding suppression for snakeyaml issue

---

dependency-check-suppressions.xml

Extend cve suppressions

---

infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/variables.tf

added db config, added demo.tfvars file for demo

---

dependency-check-suppressions.xml

new snakeyaml cve

---

dependency-check-suppressions.xml

Suppressed - CVE-2022-42004, CVE-2022-42003

---

cve-resolution-strategy.gradle

added new version of tomcat embed core and websocket

---

cve-resolution-strategy.gradle

upgrade snakeyaml

---

api/src/main/java/uk/gov/hmcts/bar/api/converters/PaymentInstructionsCsvConverter.java

Sonar critical issues fixes

---

dependency-check-suppressions.xml

CVE Suppression Date Update

---

build.gradle
cve-resolution-strategy.gradle
dependency-check-suppressions.xml

owasp dependency check version upgrade

---

infrastructure/variables.tf

set default value

---

cve-resolution-strategy.gradle
dependency-check-suppressions.xml

upgrading to newest minor version of jackson databind

---

charts/bar-api/Chart.yaml
cve-resolution-strategy.gradle
dependency-check-suppressions.xml

testing upgrade for apache commons fileupload 1.3.3->1.5

---

api/build.gradle
build.gradle
client/build.gradle

This is a follow up to a previous ticket.
Minor change to resolve sonarqube issues in master.
```
[ ] Yes
[x] No
```

Fix bar api master

---

cve-resolution-strategy.gradle
dependency-check-suppressions.xml

PAY-6040-CVE-fixes

---

api/build.gradle
api/src/main/resources/bootstrap.yaml
build.gradle
charts/bar-api/Chart.yaml
charts/bar-api/values.yaml

https://tools.hmcts.net/jira/browse/PAY-6040
Upgrade gradle-git-properties and transitive dependancy library is no longer available.
```
[ ] Yes
[x] No
```

PAY-6040: Update version to gradle-git-properties.

---

api/build.gradle
api/src/main/resources/application.properties
api/src/test/java/uk/gov/hmcts/bar/api/controllers/errors/ControllerExceptionHandlerTest.java
build.gradle
cve-resolution-strategy.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6040
Fix master pipeline, remove property volume code. 
```
[ ] Yes
[x] No
```

Fix to master pipeline.

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6080
Update to add CVE suppression as no known fix.
```
[ ] Yes
[x] No
```

PAY-6040: Add latest CVE suppresssion

---

Jenkinsfile_CNP
Jenkinsfile_nightly
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6406
Suppressing CVE-2023-34036, removing PR pointing so it picks up internal apps in Preview.
```
[ ] Yes
[x] No
```

PAY-6406: Update to suppress CVE-2023-34036

---

dependency-check-suppressions.xml

PAY-6429
CVE-2023-34035 fix
```
[ ] Yes
[ x ] No
```

CVE-2023-34035 fix

---

build.gradle
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6443
Add CVE fix and suppressions. 
```
[ ] Yes
[x] No
```

PAY-6443: Pipeline fixes

---

dependency-check-suppressions.xml

PAY_6515
CVE-2023-41080 FIX master
```
[ ] Yes
[ x ] No
```

CVE-2023-41080 FIX master

---

.github/renovate.json

rennovate fix
PAY-6542
```
[ ] Yes
[ x ] No
```

rennovate fix

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6577
Suppress CVE-2023-34047

PAY-6577_CVE-2023-34047

---

dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/PAY-6614
CVE supressions
- [ X] Does this PR introduce a breaking change

PAY-6614 suppress tomcat CVEs

---

charts/bar-api/Chart.yaml
charts/bar-api/values.yaml
dependency-check-suppressions.xml

version update

---

infrastructure/main.tf
infrastructure/provider.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PAY-6576
Flexible Server DB

PAY-6576 Flexible DB Creation

---

dependency-check-suppressions.xml
infrastructure/main.tf

PAY-6576
rename of flexible server

PAY-6576 Flexible DB rename

---

charts/bar-api/Chart.yaml
charts/bar-api/values.yaml

PAY-6576 Secrets

---

infrastructure/sdp.tf

https://tools.hmcts.net/jira/browse/PAY-6680
Setup SDP user for new flexible server db

PAY-6680 SDP user setup

---

charts/bar-api/Chart.yaml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/PAY-6701
Force access to new flexible server tables

PAY-6701-force access

---

infrastructure/sdp.tf

[PAY-6702](https://tools.hmcts.net/jira/browse/PAY-6702)
Amend sdp user access

PAY-6702-amend sdp user access

---

charts/bar-api/Chart.yaml
charts/bar-api/values.yaml
infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PAY-6659
Decommision v11 db

PAY-6659-decommission v11 db for Bar

---

infrastructure/main.tf
infrastructure/provider.tf

https://tools.hmcts.net/jira/browse/PAY-6659
Correct azurerm feature.

PAY-6659: Correct azurerm feature

---

api/src/main/java/uk/gov/hmcts/bar/api/auth/SiteValidationFilter.java
api/src/test/java/uk/gov/hmcts/bar/api/componenttests/SwaggerPublisher.java

https://tools.hmcts.net/jira/browse/PAY-6427
Testing Swagger and adding publishing test."

PAY-6427: Update to add swagger test

---

.github/workflows/ci.yml

https://tools.hmcts.net/jira/browse/PAY-7563
Update Cache Storage to v4 and Java Setup to v4.
```
[ ] Yes
[x] No
```

PAY-7535: Minor update to Storage Cache v4
